#!/usr/bin/env python3
"""Update only the CardsAndDice appendix in the repository's authoritative notices.

The appendix is its own section just before the closing "questions" block of
THIRD-PARTY-NOTICES.txt; everything else in that file is left exactly as it is.
"""
from pathlib import Path
import json, hashlib
root=Path(__file__).resolve().parents[2]
assets=root/'src/CodeBrix.Platform.GameEngine.CardsAndDice.Assets'
entries=json.loads((assets/'catalog.json').read_text(encoding='utf-8'))
SEP='='*80
marker='CARDSANDDICE EMBEDDED ASSETS — PROVENANCE APPENDIX\n'
closing=SEP+'\n\nIf you have any questions about any third-party code'
p=root/'THIRD-PARTY-NOTICES.txt'
# Keep the file's own line endings (CRLF in a Windows checkout under core.autocrlf), so only the appendix changes.
newline='\r\n' if b'\r\n' in p.read_bytes() else '\n'
text=p.read_text(encoding='utf-8')
if marker in text:
 i=text.index(marker)
 start=i-len(SEP)-1 if text[max(0,i-len(SEP)-1):i]==SEP+'\n' else i
 j=text.find(closing,i)
 text=text[:start].rstrip('\n')+'\n'+('\n'+text[j:] if j!=-1 else '')
k=text.index(closing)
notice='''
The optional CardsAndDice package includes the separate, non-packable Assets
assembly. It redistributes the resources listed below inside that assembly.
No artist credit screen or individual author lookup is required by these asset
permissions. The normal MIT library copyright/license notice still applies.

A. KENNEY — CC0-1.0
Author/distributor: Kenney (Kenney Vleugels), https://kenney.nl/
Source: Jeremy Ellis's purchased Kenney Game Assets All-in-1 3.6.0 bundle.
Included: Board Game Icons 1.1 (Vector/Icons), Board Game Info 1.0
(Vector/Fantasy), and five Casino Audio 1.1 effects. Files are unmodified.
Their pack License.txt files explicitly designate Creative Commons Zero and
state that credit is optional. Payment is not the permission basis: CC0 is.
https://kenney.nl/assets/board-game-icons
https://kenney.nl/assets/board-game-info
https://kenney.nl/assets/casino-audio
License: https://creativecommons.org/publicdomain/zero/1.0/legalcode
Copies of the three original license files are under
src/CodeBrix.Platform.GameEngine.CardsAndDice.Assets/Provenance/.

B. TRADITIONAL PLAYING CARDS — CC0-1.0
Author: Adrian Kennard (RevK). https://www.me.uk/cards/
The creator designates the cards CC0 and explicitly says attribution is not
required. Court designs are based on nineteenth-century Goodall & Son cards.
Only the standard 52-card English-suit deck with Plain ace was imported.
No Alteran characters or other alternate branded variants are included.
Source SVG roots were extracted from the creator's generated deck page;
vector artwork was not otherwise changed. Original joker images in this
package are our own geometric designs, not third-party playing-card variants.
License: https://creativecommons.org/publicdomain/zero/1.0/legalcode

C. HISTORICAL RIDER–WAITE–SMITH TAROT — PUBLIC DOMAIN
Artist: Pamela Colman Smith (1878–1951), conceived with Arthur Edward Waite
(1857–1942). Original Pam-A edition, 1909/1910, not a modern recoloring.
Source set: https://commons.wikimedia.org/wiki/Category:Rider-Waite-Smith_tarot_deck_(TaionWC)
Scans uploaded by TaionWC; file pages identify the source as muzendo.jp/blog/.
Each imported file was checked for a public-domain designation. Individual
file-page and original-image URLs, and hashes, appear below. The Commons
file pages designate the work public domain in the US through early publication
and in its country of origin through expired copyright. Smith's death in 1951
also places the original drawings beyond life-plus-70 terms as of 2022.
This records the basis used here, not a claim about every country's term or
about later editions, recolorings, card backs, or brands.
Public Domain Mark: https://creativecommons.org/publicdomain/mark/1.0/

Modification: scanned JPEGs were converted into genuine colored SVG paths
using vtracer 0.6.15, after Pillow 12.3.0 resizing to fit 620 x 1000.
Wikimedia cached 960px renditions were used when originals were rate limited;
the manifest Source URL identifies the exact downloaded rendition.
Trace settings: stacked colors, spline, filter_speckle=8, color_precision=5,
layer_difference=24, corner_threshold=60, length_threshold=4,
max_iterations=10, splice_threshold=45, path_precision=2.
No raster images are embedded in those SVGs. Original print/paper texture is
retained; automated traces are not hand-redrawn restoration artwork.
The tools are build-time utilities, not vendored or redistributed dependencies.
The source and output SHA-256 values below identify the exact conversion.
Additional per-file factual evidence is in the repository at
src/CodeBrix.Platform.GameEngine.CardsAndDice.Assets/tarot-provenance.json.

D. ORIGINAL GEOMETRIC ARTWORK — MIT
Simple playing cards, two jokers, card-back frames, dice silhouettes and dotted die faces, numeric
value glyphs and geometric elemental/alchemical symbols were generated by
our tools/cards-and-dice/generate-originals.py. They are original repository
artwork covered by the root MIT LICENSE, copyright 2026 Jeremy Ellis and
contributors. Dynamic sample cards use CardComposer and these same symbols.
No game-icons.net artwork, attribution-required icon set, or downloaded font
is incorporated in these generated SVG files.

E. STAR OF ISHTAR — PUBLIC DOMAIN (PD-self)
Artist: Raphael 75 (Raphael). Published 8 December 2009.
File page: https://commons.wikimedia.org/wiki/File:Ishtar-star-symbol.svg
Reviewed revision: https://commons.wikimedia.org/w/index.php?title=File:Ishtar-star-symbol.svg&oldid=1210908454
Original: https://upload.wikimedia.org/wikipedia/commons/f/f9/Ishtar-star-symbol.svg
The creator releases this work into the public domain worldwide, with a fallback
permission to use it for any purpose without conditions where dedication is not
possible. No attribution condition is imposed. The original SVG is embedded as
symbols/historical/ishtar-star.svg, byte-for-byte unchanged.
The royal, celestial and crimson card backs incorporate its original vector
geometry and colors, scaled to 154 x 154 and centered inside an enlarged medallion in the existing frame.
Those composite backs retain MIT-covered original frames around this public-domain
symbol. Their SourceSHA256 identifies the input star; their SHA256 identifies the
complete composite SVG. No external links or raster image loads are needed to draw.

PER-FILE MANIFEST
Paths are relative to src/CodeBrix.Platform.GameEngine.CardsAndDice.Assets/Resources.
SourceSHA256 is the pre-conversion input; SHA256 identifies the shipped bytes.
For unchanged files they coincide. The runtime catalog embeds these same data.

'''
for e in entries:
 data=(assets/'Resources'/e['Key']).read_bytes()
 assert hashlib.sha256(data).hexdigest()==e['Sha256'],e['Key']
 notice+=f"{e['Key']}\n  License: {e['License']}\n  Source: {e['Source']}\n  SourceSHA256: {e['SourceSha256']}\n  SHA256: {e['Sha256']}\n"
p.write_text(text[:k]+SEP+'\n'+marker+notice+'\n'+text[k:],encoding='utf-8',newline=newline)
print(f'Updated notices for {len(entries)} assets')
